title: Ismail otukoya
#logo: /assets/img/headshot_circle.png
#description: Explore impactful projects showcasing my expertise in machine learning, statistical analysis, and data visualization. From predictive modeling to recommendation systems, each project delivers actionable insights with a commitment to ethics.
#show_downloads: true
theme: jekyll-theme-minimal
