title: Ismail otukoya
logo: /assets/96750333.jpeg
description: Explore impactful projects showcasing my expertise in machine learning and data visualization.  
#show_downloads: true
theme: jekyll-theme-minimal
